version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.3.8-node
        environment:
          RACK_ENV:  test
          RAILS_ENV: test
    steps:
      - checkout
      - run: bundle check || bundle install --jobs=4
      - run: bundle exec rspec
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
